# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-09-16 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique='True')),
                ('details', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='webs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webpage', models.URLField(unique='True')),
                ('email', models.EmailField(max_length=254)),
                ('namew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnapp.info')),
            ],
        ),
    ]
